// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXcCoSLr471S9GAX68_-EHGm3HgVLX_Mc',
    appId: '1:162330401292:web:551e65d6290e06aca1ac29',
    messagingSenderId: '162330401292',
    projectId: 'dementia-assistant-13cd2',
    authDomain: 'dementia-assistant-13cd2.firebaseapp.com',
    storageBucket: 'dementia-assistant-13cd2.firebasestorage.app',
    measurementId: 'G-DH5GY3TQ9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtZDHfC4IrTh1X3uGUZYclR5fBMipbwII',
    appId: '1:162330401292:android:9dde58d1acf7bd4ca1ac29',
    messagingSenderId: '162330401292',
    projectId: 'dementia-assistant-13cd2',
    storageBucket: 'dementia-assistant-13cd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANJzD9XXmlBfVbG0z8tsdv1lrq09mzmaI',
    appId: '1:162330401292:ios:224347b252d90ee4a1ac29',
    messagingSenderId: '162330401292',
    projectId: 'dementia-assistant-13cd2',
    storageBucket: 'dementia-assistant-13cd2.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANJzD9XXmlBfVbG0z8tsdv1lrq09mzmaI',
    appId: '1:162330401292:ios:224347b252d90ee4a1ac29',
    messagingSenderId: '162330401292',
    projectId: 'dementia-assistant-13cd2',
    storageBucket: 'dementia-assistant-13cd2.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXcCoSLr471S9GAX68_-EHGm3HgVLX_Mc',
    appId: '1:162330401292:web:2af3046b9e1ecb0aa1ac29',
    messagingSenderId: '162330401292',
    projectId: 'dementia-assistant-13cd2',
    authDomain: 'dementia-assistant-13cd2.firebaseapp.com',
    storageBucket: 'dementia-assistant-13cd2.firebasestorage.app',
    measurementId: 'G-78Y2N0ZWPN',
  );

}